export const ROUTINE_FOCUS_OPTIONS = [
  "Strength",
  "Hypertrophy",
  "Endurance",
  "Mobility",
  "Power",
  "Fat Loss",
  "General Fitness",
  "Athletic Performance",
  "Rehabilitation",
];

export const ROUTINE_WORKOUT_TYPE_OPTIONS = [
  "Full Body",
  "Upper Body",
  "Lower Body",
  "Push",
  "Pull",
  "Legs",
  "Chest",
  "Back",
  "Shoulders",
  "Arms",
  "Core",
  "Glutes",
  "Cardio",
  "HIIT",
];

export const TARGET_MUSCLE_OPTIONS = [
  "Chest",
  "Back",
  "Shoulders",
  "Biceps",
  "Triceps",
  "Forearms",
  "Core",
  "Glutes",
  "Quadriceps",
  "Hamstrings",
  "Calves",
  "Adductors",
  "Abductors",
  "Full Body",
];

export const EQUIPMENT_OPTIONS = [
  "Bodyweight",
  "Barbell",
  "Dumbbells",
  "Bench",
  "Rack",
  "Smith Machine",
  "Cable Machine",
  "Pull-Up Bar",
  "EZ Bar",
  "Kettlebell",
  "Resistance Band",
  "Medicine Ball",
  "Leg Press",
  "Machine",
  "Trap Bar",
  "Landmine",
];
